name: Go

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: isbang/compose-action@v1.5.1
              with:
                  compose-file: "./docker-compose.yml"
                  down-flags: "--volumes"

            - name: Create .env for CI
              run: cp .env.ci .env

            - name: Build application with Docker Compose
              run: docker-compose up -d

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...
